
const SITE = {
  email: "salahfaisal589@gmail.com",
  scholar: "https://scholar.google.com/citations?hl=ar&user=kV3STigAAAAJ",
  orcid: "https://orcid.org/0009-0000-9485-7467"
};

const publications = [
  {year:2026,category:"published-2026",status:"Published · IEEE Xplore",title:"Control-Oriented Design and Performance Evaluation of a Three-Terminal Storage-Assisted EV Fast-Charging System with an Interleaved Bidirectional Buck–Boost Converter",authors:"Salah F. S. Saeed, Radhwan A. A. Saleh, Abdullah Haidar, Mustafa Ghaleb, Humam AbuAlkebash, & Mubaarak A. A. Saif",venue:"6th International Conference on Emerging Smart Technologies and Applications (eSmarTA-2026), IEEE",link:"https://lnkd.in/dFqDeHdN",linkLabel:"IEEE Xplore / DOI"},
  {year:2026,category:"published-2026",status:"Published · IEEE Xplore",award:"Best Paper Award",title:"Toward Trust-by-Design in Federated Learning for Healthcare: A Taxonomic Review of Privacy, Explainability, and Accountability",authors:"Radhwan A. A. Saleh, Salah F. S. Saeed, Mona A. H. Al-Ariqi, Malak E. T. Ahmed, Malak M. A. Yahya, & Mustafa Ghaleb",venue:"6th International Conference on Emerging Smart Technologies and Applications (eSmarTA-2026), IEEE",link:"https://doi.org/10.1109/eSmarTA70636.2026.11652200",linkLabel:"DOI"},
  {year:2026,category:"published-2026",status:"Published · IEEE Xplore",title:"Data-Driven Deep Learning for Imaging Through Scattering Media: Architectures, Learning Paradigms, and Methodological Frontiers",authors:"Radhwan A. A. Saleh, Salah F. S. Saeed, Malak M. N. Al-Koshab, Alzahraa F. M. Almakhathy, Abdullah Haidar, Kerem Kucuk, & Mustafa Ghaleb",venue:"6th International Conference on Emerging Smart Technologies and Applications (eSmarTA-2026), IEEE",link:"https://doi.org/10.1109/eSmarTA70636.2026.11652149",linkLabel:"DOI"},
  {year:2026,category:"published-2026",status:"Published · IEEE Xplore",title:"A Review of Electric Vehicle Charging Systems: Converter Architectures, Control Optimization, and PV-Integrated Energy Management",authors:"Mubaarak A. A. Saif, Salah F. S. Saeed, Abdullah Haidar, Alzahraa F. M. Almakhathy, Malak M. N. Al-Koshab, & Nora H. A. Qasem",venue:"6th International Conference on Emerging Smart Technologies and Applications (eSmarTA-2026), IEEE",link:"https://doi.org/10.1109/eSmarTA70636.2026.11652317",linkLabel:"DOI"},
  {year:2025,category:"published-2025",status:"Published · IEEE",title:"Advances in Error Compensation for Robotic Manipulators: A Systematic Review from Geometric Calibration to AI-Driven Hybrid Control",authors:"R. A. Saleh, S. F. Nasser, & T. S. Abdullah",venue:"5th International Conference on Emerging Smart Technologies and Applications (eSmarTA-2025), IEEE, pp. 1–10",link:"https://doi.org/10.1109/eSmarTA66764.2025.11131700",linkLabel:"DOI"},
  {year:2025,category:"published-2025",status:"Published · IEEE",title:"A Survey on Camera-Based Measurement Systems: Techniques, Applications, and Challenges",authors:"R. A. Saleh, S. F. Nasser, M. M. Al Mashwali, E. M. Taha, & O. A. Al-Noor",venue:"5th International Conference on Emerging Smart Technologies and Applications (eSmarTA-2025), IEEE, pp. 1–9",link:"https://doi.org/10.1109/eSmarTA66764.2025.11132174",linkLabel:"DOI"},
  {year:2025,category:"published-2025",status:"Published · IEEE",title:"A Comprehensive Review of Transcranial Direct Current Stimulation (tDCS): Mechanisms, Cognitive Effects, Applications, and Future Directions",authors:"R. A. Saleh, S. F. Nasser, A. F. Almakhathy, & M. M. Al-Koshab",venue:"5th International Conference on Emerging Smart Technologies and Applications (eSmarTA-2025), IEEE, pp. 1–8",link:"https://doi.org/10.1109/eSmarTA66764.2025.11132143",linkLabel:"DOI"},
  {year:2025,category:"published-2025",status:"Published · IEEE",title:"Advancements in Robotic Arm Technologies: Precision, Intelligence, and Cross-Sector Applications",authors:"R. A. Saleh, Y. Alqudsi, A. A. Al-Hajj, A. A. Abdullah, S. F. Nasser, & M. A. Amrani",venue:"5th International Conference on Emerging Smart Technologies and Applications (eSmarTA-2025), IEEE, pp. 1–10",link:"https://doi.org/10.1109/eSmarTA66764.2025.11132178",linkLabel:"DOI"},
  {year:"Current",category:"in-preparation",status:"In Preparation",title:"Hybrid Geometric–Sliding Mode Control of Quadrotor UAVs with Disturbance Rejection Optimized",authors:"Collaborative research work",venue:"Algorithm development, optimization refinement, and validation in progress"},
  {year:"Current",category:"in-preparation",status:"In Preparation",title:"Optimization-Assisted Model Predictive Control for Grid-Compliant PV-Integrated Bidirectional EV Fast-Charging Systems",authors:"Collaborative research work",venue:"Controller development and simulation-based validation in progress"},
  {year:"Current",category:"in-preparation",status:"In Preparation",title:"Reliability-Constrained Multi-Objective Optimization of an Off-Grid PV–Wind–Diesel–Battery Hybrid Energy System: A HOMER-Benchmarked Cost–Renewability Assessment",authors:"Collaborative research work",venue:"Optimization and benchmarking in progress"},
  {year:"Current",category:"in-preparation",status:"In Preparation",title:"Explainable and Privacy-Preserving Federated Learning in Healthcare: A Systematic Review and Taxonomic Synthesis",authors:"Review manuscript",venue:"Collaborative review and pre-submission refinement"},
  {year:"Current",category:"in-preparation",status:"In Preparation",title:"Security Digital Twins for SOC Engineering: Threat Simulation, Detection Content Generation, and Response Validation: A Systematic Review",authors:"Review manuscript",venue:"Collaborative review and pre-submission refinement"},
  {year:"Current",category:"in-preparation",status:"In Preparation",title:"Automating Cybersecurity Penetration Testing Tasks with AI Agents Using LLMs: A Systematic Review",authors:"Review manuscript",venue:"Collaborative review and pre-submission refinement"}
];

const projects = [
  {id:"robot-arm",category:"robotics",status:"Completed · B.Sc. Graduation Project",title:"Manipulator Robot Error Correction Using Computer Vision",summary:"Computer-vision-based work focused on measuring and correcting robotic-manipulator positioning error to support precision-oriented robotics.",tags:["Robotics","Computer Vision","Control"],objective:"Investigate a computer-vision-based approach for measuring and correcting manipulator positioning error.",methods:"Camera-based measurement, error analysis, calibration-oriented reasoning, and correction workflow.",tools:"Computer vision, robotics, engineering analysis",related:"Graduation project and robotic-manipulator error-compensation research."},
  {category:"robotics",status:"In Preparation",title:"Hybrid Geometric–Sliding Mode Control of Quadrotor UAVs with Disturbance Rejection Optimized",summary:"Ongoing research on robust quadrotor control with disturbance rejection and optimization-assisted refinement.",tags:["UAV","Geometric Control","Sliding Mode","Optimization"],objective:"Improve robust trajectory control and disturbance rejection for quadrotor UAVs.",methods:"Hybrid control design and optimization-assisted parameter refinement.",tools:"MATLAB/Simulink, control modeling, optimization",related:"Research manuscript in preparation."},
  {category:"energy",status:"In Preparation",title:"Optimization-Assisted Model Predictive Control for Grid-Compliant PV-Integrated Bidirectional EV Fast-Charging Systems",summary:"Control-oriented research integrating predictive control, optimization, PV support, bidirectional charging, and grid-interface requirements.",tags:["EV Charging","MPC","PV","Optimization"],objective:"Develop a grid-compliant predictive-control framework for PV-integrated bidirectional EV charging.",methods:"System modeling, MPC formulation, constraints, optimization, and simulation-based validation.",tools:"MATLAB/Simulink, power electronics, optimization",related:"Research manuscript in preparation."},
  {category:"energy",status:"In Preparation",title:"Reliability-Constrained Multi-Objective Optimization of an Off-Grid PV–Wind–Diesel–Battery Hybrid Energy System",summary:"HOMER-benchmarked optimization research balancing reliability, cost, and renewable-energy contribution in an off-grid hybrid energy system.",tags:["HRES","HOMER","Reliability","Multi-Objective Optimization"],objective:"Evaluate reliability–cost–renewability trade-offs in an off-grid hybrid energy system.",methods:"HOMER benchmarking and multi-objective metaheuristic optimization.",tools:"HOMER, MATLAB, optimization",related:"Research manuscript in preparation."},
  {category:"ai",status:"Systematic Review · In Preparation",title:"Explainable and Privacy-Preserving Federated Learning in Healthcare",summary:"Review work examining explainability, privacy, trust, and deployment considerations in federated healthcare AI.",tags:["Federated Learning","XAI","Privacy","Healthcare AI"],objective:"Synthesize methodological patterns and gaps across privacy-preserving and explainable federated healthcare systems.",methods:"Systematic review and taxonomic synthesis.",tools:"Literature synthesis, taxonomy design, academic writing",related:"Review manuscript in preparation."},
  {category:"cybersecurity",status:"Systematic Review · In Preparation",title:"Security Digital Twins for SOC Engineering",summary:"Review research on the use of security digital twins for threat simulation, detection-content generation, and response validation in SOC workflows.",tags:["Security Digital Twins","SOC","Threat Simulation","Cybersecurity"],objective:"Assess how security digital twins can support realistic SOC engineering and validation.",methods:"Systematic literature review and methodological comparison.",tools:"Cybersecurity research, taxonomy design, evidence synthesis",related:"Review manuscript in preparation."},
  {category:"cybersecurity",status:"Systematic Review · In Preparation",title:"Automating Cybersecurity Penetration Testing Tasks with AI Agents Using LLMs",summary:"Review research examining AI-agent and LLM-assisted automation of penetration-testing tasks and the methodological limits of current approaches.",tags:["AI Agents","LLMs","Penetration Testing","Cybersecurity"],objective:"Map where AI agents and LLMs are being used in penetration-testing workflows and assess validation quality.",methods:"Systematic review and comparative methodological analysis.",tools:"LLMs, AI agents, cybersecurity research",related:"Review manuscript in preparation."}
];

const mediaItems = [
  {category:"robotics",title:"Manipulator Robot Error Correction",description:"Graduation-project documentation for computer-vision-based manipulator error measurement and correction.",asset:"/assets/work/robot-arm-computer-vision-cover.jpg",type:"image",related:"/projects/#robot-arm"},
  {category:"energy",title:"EV Fast-Charging Simulation",description:"MATLAB/Simulink model and selected simulation views from EV fast-charging research.",asset:"/assets/work/ev-fast-charging-simulink-cover.jpg",type:"image",related:"/projects/"},
  {category:"embedded",title:"Embedded Systems & IoT",description:"Selected practical work using microcontrollers, sensors, actuators, and connectivity workflows.",asset:"/assets/work/embedded-systems-iot-cover.jpg",type:"image",related:"/teaching/"},
  {category:"laboratory",title:"Robotics Laboratory Development",description:"Selected evidence of laboratory organization, equipment readiness, and hands-on STEM activities.",asset:"/assets/work/robotics-lab-development-cover.jpg",type:"image",related:"/experience/"},
  {category:"teaching",title:"Research Mentorship",description:"Selected documentation from scientific-research and academic-writing mentorship activities.",asset:"/assets/work/research-mentorship-cover.jpg",type:"image",related:"/teaching/"},
  {category:"laboratory",title:"Physics Laboratory & Instrumentation",description:"Laboratory preparation, measurement instruments, electronics, and practical technical support.",asset:"/assets/work/physics-lab-instrumentation-cover.jpg",type:"image",related:"/experience/"},
  {category:"industrial",title:"Industrial Training — Nadfood",description:"Selected technical evidence from engineering-department industrial training.",asset:"/assets/work/industrial-training-nadfood-cover.jpg",type:"image",related:"/experience/#industrial-exposure"},
  {category:"industrial",title:"Industrial Training — GenPack",description:"Selected evidence from cooperative industrial training in production and plant operations.",asset:"/assets/work/industrial-training-genpack-cover.jpg",type:"image",related:"/experience/#industrial-exposure"}
];

const achievements = [
  {date:"August 2026",title:"Best Paper Award — eSmarTA-2026",description:"Toward Trust-by-Design in Federated Learning for Healthcare: A Taxonomic Review of Privacy, Explainability, and Accountability was selected among the Best Paper Award recipients at eSmarTA-2026.",award:true},
  {date:"2016–2017",id:"academic-distinction",title:"Academic Distinction — First in Cohort and Second Nationally",description:"Vocational Professional Diploma in Industrial Control Systems / Electronics, Technical Industrial Institute. Cumulative grade: 92.27% (Excellent)."},
  {date:"2014–2016",title:"First Rank in Cohort",description:"Recognized for excellent academic and practical performance during the first and second vocational levels in Industrial Control Systems / Electronics."},
  {date:"2026",title:"Scientific Research & Academic Writing Program Recognition",description:"Recognition for research mentorship, academic-writing guidance, critical reading, student research engagement, and publication-oriented academic activities."},
  {date:"2026",title:"Professional Excellence & Dedicated Service",description:"Recognition for professional service, reliability, teamwork, problem solving, teaching, technical training, STEM education, and academic guidance."},
  {date:"2026",title:"Laboratory Development Recognition",description:"Recognition for laboratory development, equipment organization, experiment preparation, troubleshooting, safety-aware practice, and hands-on STEM learning."},
  {date:"2023",title:"Teaching Excellence & Physics Laboratory Development",description:"Recognition for secondary-level teaching, student guidance, physics laboratory preparation, electronic experiments, and practical learning."}
];

const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];

function escapeHTML(value="") { const d=document.createElement("div"); d.textContent=value; return d.innerHTML; }

function initYear(){ const el=$("#year"); if(el) el.textContent=new Date().getFullYear(); }
function initProfileImage(){ const img=$("#profilePhoto"), wrap=$("#profilePhotoWrap"); if(!img||!wrap)return; img.addEventListener("error",()=>wrap.classList.add("image-error")); if(img.complete && img.naturalWidth===0) wrap.classList.add("image-error"); }
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem("theme",theme);$$('[data-theme-toggle],#themeToggle').forEach(b=>{const icon=b.querySelector('span:first-child'); if(icon) icon.textContent=theme==='dark'?'☀':'◐'; if(b.classList.contains('icon-only')) b.textContent=theme==='dark'?'☀':'◐';});}
function initTheme(){const stored=localStorage.getItem("theme");const preferred=window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';setTheme(stored||preferred);$$('[data-theme-toggle],#themeToggle').forEach(b=>b.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')));}
function initMobileNav(){const toggle=$("#menuToggle"),side=$("#sidebar"),backdrop=$("#sidebarBackdrop");if(!toggle||!side||!backdrop)return;const close=()=>{side.classList.remove('open');backdrop.hidden=true;document.body.classList.remove('nav-open');toggle.setAttribute('aria-expanded','false')};toggle.addEventListener('click',()=>{const open=!side.classList.contains('open');side.classList.toggle('open',open);backdrop.hidden=!open;document.body.classList.toggle('nav-open',open);toggle.setAttribute('aria-expanded',String(open))});backdrop.addEventListener('click',close);$$('.side-nav a').forEach(a=>a.addEventListener('click',close));window.addEventListener('keydown',e=>{if(e.key==='Escape')close()});}
function initReveal(){const els=$$('.reveal');if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('visible'));return;}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});els.forEach(e=>io.observe(e));}
function initScrollUI(){const bar=$("#scrollProgress"),top=$("#backToTop");const update=()=>{const y=window.scrollY||0;const h=document.documentElement.scrollHeight-innerHeight;if(bar)bar.style.width=`${h>0?y/h*100:0}%`;if(top)top.classList.toggle('show',y>500)};addEventListener('scroll',update,{passive:true});update();if(top)top.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));}
function showToast(msg){const t=$("#toast");if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2200);}
function initCopyEmail(){const b=$("#copyEmail");if(!b)return;b.addEventListener('click',async()=>{const email=b.dataset.email||SITE.email;try{await navigator.clipboard.writeText(email);showToast('Email copied to clipboard')}catch{showToast(email)}});}
function initCvAvailability(){ $$('.cv-link').forEach(async a=>{try{const r=await fetch(a.getAttribute('href'),{method:'HEAD'});if(!r.ok){a.classList.add('unavailable');a.title='Upload Salah_Faisal_CV.pdf to enable this link';a.addEventListener('click',e=>{e.preventDefault();showToast('CV file is not uploaded yet')})}}catch{}}); }
function initFilters(){ $$('.filter-toolbar').forEach(toolbar=>{const targetId=toolbar.dataset.filterTarget;const target=document.getElementById(targetId);if(!target)return;toolbar.addEventListener('click',e=>{const b=e.target.closest('.filter-btn');if(!b)return;$$('.filter-btn',toolbar).forEach(x=>x.classList.remove('active'));b.classList.add('active');const filter=b.dataset.filter;$$('.filter-item',target).forEach(item=>{const cats=(item.dataset.category||'').split(/\s+/);item.classList.toggle('is-hidden',filter!=='all'&&!cats.includes(filter));});});});}

function renderPublications(){const root=$("#publicationsList");if(!root)return;let currentYear=null,index=0;root.innerHTML='';for(const p of publications){if(p.year!==currentYear){currentYear=p.year;const h=document.createElement('div');h.className='publication-year-heading';h.textContent=String(currentYear);root.appendChild(h);}index++;const el=document.createElement('article');el.className='publication-record filter-item';el.dataset.category=p.category;const statusClass=p.category==='in-preparation'?'status-prep':'status-published';el.innerHTML=`<div class="publication-index">${String(index).padStart(2,'0')}</div><div><div><span class="status-badge ${statusClass}">${escapeHTML(p.status)}</span>${p.award?`<span class="status-badge award-badge">${escapeHTML(p.award)}</span>`:''}</div><h3>${escapeHTML(p.title)}</h3><p class="pub-authors">${escapeHTML(p.authors)}</p><p class="pub-venue">${escapeHTML(p.venue)}</p>${p.link?`<div class="pub-actions"><a href="${p.link}" target="_blank" rel="noopener">${escapeHTML(p.linkLabel||'External link')} ↗</a></div>`:''}</div>`;root.appendChild(el);}}

function renderProjects(){const root=$("#projectsList");if(!root)return;root.innerHTML=projects.map((p,i)=>`<article class="project-record filter-item" ${p.id?`id="${p.id}"`:''} data-category="${p.category}"><div class="project-top"><div><p class="record-type">${escapeHTML(p.status)}</p><h3>${escapeHTML(p.title)}</h3></div><span class="publication-index">${String(i+1).padStart(2,'0')}</span></div><p class="project-summary">${escapeHTML(p.summary)}</p><div class="project-tags">${p.tags.map(t=>`<span>${escapeHTML(t)}</span>`).join('')}</div><details class="project-details"><summary>Project details</summary><dl><div><dt>Objective</dt><dd>${escapeHTML(p.objective)}</dd></div><div><dt>Methods</dt><dd>${escapeHTML(p.methods)}</dd></div><div><dt>Tools</dt><dd>${escapeHTML(p.tools)}</dd></div><div><dt>Related work</dt><dd>${escapeHTML(p.related)}</dd></div></dl></details></article>`).join('');}

async function assetExists(url){try{const r=await fetch(url,{method:'HEAD',cache:'no-store'});return r.ok}catch{return false}}
async function renderMedia(){const root=$("#mediaList"),empty=$("#mediaEmptyState");if(!root)return;const existing=[];for(const item of mediaItems){if(await assetExists(item.asset))existing.push(item);}if(!existing.length){if(empty)empty.hidden=false;return;}root.innerHTML=existing.map((m,i)=>`<article class="media-card filter-item" data-category="${m.category}"><button class="media-thumb" type="button" data-media-src="${m.asset}" data-media-type="${m.type}" data-media-title="${escapeHTML(m.title)}"><img src="${m.asset}" alt="${escapeHTML(m.title)}" loading="lazy"></button><div class="media-body"><span class="media-category">${escapeHTML(m.category)}</span><h3>${escapeHTML(m.title)}</h3><p>${escapeHTML(m.description)}</p><div class="media-actions"><button type="button" data-media-src="${m.asset}" data-media-type="${m.type}" data-media-title="${escapeHTML(m.title)}">View media</button><a href="${m.related}">Related section →</a></div></div></article>`).join('');initMediaModal();}
function initMediaModal(){const modal=$("#mediaModal"),body=$("#mediaModalBody"),title=$("#mediaModalTitle");if(!modal||!body||!title)return;const open=(src,type,label)=>{title.textContent=label||'Media preview';body.innerHTML=type==='video'?`<video controls preload="metadata"><source src="${src}" type="video/mp4"></video>`:`<img src="${src}" alt="${escapeHTML(label||'Media preview')}">`;modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')};const close=()=>{modal.classList.remove('show');modal.setAttribute('aria-hidden','true');body.innerHTML='';document.body.classList.remove('modal-open')};$$('[data-media-src]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.mediaSrc,b.dataset.mediaType,b.dataset.mediaTitle)));$$('[data-close-modal]',modal).forEach(b=>b.addEventListener('click',close));window.addEventListener('keydown',e=>{if(e.key==='Escape')close()});}
function renderAchievements(){const root=$("#achievementsList");if(!root)return;root.innerHTML=achievements.map(a=>`<article class="achievement-record" ${a.id?`id="${a.id}"`:''}><time>${escapeHTML(a.date)}</time><div><h3>${escapeHTML(a.title)}</h3><p>${escapeHTML(a.description)}</p>${a.award?'<span class="award-mark">Award</span>':''}</div></article>`).join('');}

document.addEventListener('DOMContentLoaded',()=>{initYear();initProfileImage();initTheme();initMobileNav();initReveal();initScrollUI();initCopyEmail();initCvAvailability();renderPublications();renderProjects();renderAchievements();renderMedia().then(initFilters);initFilters();});
